<a href="https://colab.research.google.com/github/JaeHeee/NumPy_Tutorial/blob/master/code/%EB%B0%98%EB%B3%B5%2C_%EB%B0%B0%EC%97%B4_%EC%8C%93%EA%B8%B0%2C_%EB%B0%B0%EC%97%B4_%EB%B6%84%ED%95%A0%2C_%EB%B0%B0%EC%97%B4_%EC%A0%84%EC%B9%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 반복, 배열 쌓기, 배열 분할, 배열 전치

In [2]:
import numpy as np

## 반복

In [3]:
# ndarray를 반복하는 것은 일반적인 파이썬 배열을 반복하는 것과 매우 유사하다.
# 다차원 배열을 반복하면 첫 번째 축에 대해서 수행
# 3D 배열 (두 개의 3x4 행렬로 구성됨)
c = np.arange(24).reshape(2, 3, 4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [4]:
for m in c:
    print("아이템:")
    print(m)

아이템:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
아이템:
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [5]:
for i in range(len(c)):
    print("아이템:")
    print(c[i])

아이템:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
아이템:
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [6]:
# ndarray에 있는 모든 원소를 반복하려면 flat 속성을 사용
for i in c.flat:
    print("아이템:", i)

아이템: 0
아이템: 1
아이템: 2
아이템: 3
아이템: 4
아이템: 5
아이템: 6
아이템: 7
아이템: 8
아이템: 9
아이템: 10
아이템: 11
아이템: 12
아이템: 13
아이템: 14
아이템: 15
아이템: 16
아이템: 17
아이템: 18
아이템: 19
아이템: 20
아이템: 21
아이템: 22
아이템: 23


## 배열 쌓기

In [7]:
# 다른 배열을 쌓아야 하는 경우 넘파이는 이를 위해 몇 개의 함수를 제공
q1 = np.full((3, 4), 1.0)
q1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
q2 = np.full((4, 4), 2.0)
q2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [9]:
q3 = np.full((3, 4), 3.0)
q3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

#### vstack

In [12]:
# vstack 함수를 사용하여 수직으로 쌓는다.
# q1, q2, q3가 모두 같은 크기이므로 가능(수직으로 쌓기 때문에 수직 축은 크기가 달라도 된다.)
q4 = np.vstack((q1, q2, q3))
q4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [13]:
q4.shape

(10, 4)

#### hstack

In [14]:
# hstack을 사용해 수평으로도 쌓을 수 있다.
# q1과 q3가 모두 3개의 행을 가지고 있기 때문에 가능.
q5 = np.hstack((q1, q3))
q5

array([[1., 1., 1., 1., 3., 3., 3., 3.],
       [1., 1., 1., 1., 3., 3., 3., 3.],
       [1., 1., 1., 1., 3., 3., 3., 3.]])

In [15]:
q5.shape

(3, 8)

In [17]:
# q2는 4개의 행을 가지고 있기 때문에 q1, q3와 수평으로 쌓을 수 없다.
try:
    q6 = np.hstack((q1, q2, q3))
except ValueError as e:
    print(e)

all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 4


#### concatenate

In [18]:
# concatenate 함수는 지정한 축으로도 배열을 쌓는다.
# vstack과 동일
q7 = np.concatenate((q1, q2, q3), axis=0)
q7

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [19]:
q7.shape

(10, 4)

hstack은 axis=1으로 concatenate를 호출하는 것과 같다.

#### stack

In [20]:
# stack 함수는 새로운 축을 따라 배열을 쌓는다. 모든 배열은 같은 크기를 가져야 한다.
q8 = np.stack((q1, q3))
q8

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]])

In [21]:
q8.shape

(2, 3, 4)

## 배열 분할

In [22]:
# 분할은 쌓기의 반대
r = np.arange(24).reshape(6, 4)
r

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [23]:
# 수직으로 동일한 크기로 나눈다.
r1, r2, r3 = np.vsplit(r, 3)
r1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [24]:
r2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
r3

array([[16, 17, 18, 19],
       [20, 21, 22, 23]])

In [26]:
# split 함수는 주어진 축을 따라 배열을 분할한다.
# vsplit은 axis=0으로 split을 호출하는 것과 같다.
# hsplit은 axis=1로 split을 호출하는 것과 같다.
r4, r5 = np.hsplit(r, 2)
r4

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17],
       [20, 21]])

## 배열 전치

In [27]:
# transpose 메서드는 주어진 순서대로 축을 뒤바꾸어 ndarray 데이터에 대한 새로운 뷰를 만든다.
t = np.arange(24).reshape(4, 2, 3)
t

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [29]:
# 0, 1, 2(깊이, 높이, 너비)축을 1, 2, 0(깊이 -> 너비, 높이 -> 깊이, 너비 -> 높이) 순서로 바꾼 ndarray
t1 = t.transpose((1, 2, 0))
t1

(2, 3, 4)


array([[[ 0,  6, 12, 18],
        [ 1,  7, 13, 19],
        [ 2,  8, 14, 20]],

       [[ 3,  9, 15, 21],
        [ 4, 10, 16, 22],
        [ 5, 11, 17, 23]]])

In [30]:
t1.shape

(2, 3, 4)

In [31]:
# t.transpose((2, 1, 0)) 와 동일
t2 = t.transpose()
t2

array([[[ 0,  6, 12, 18],
        [ 3,  9, 15, 21]],

       [[ 1,  7, 13, 19],
        [ 4, 10, 16, 22]],

       [[ 2,  8, 14, 20],
        [ 5, 11, 17, 23]]])

In [32]:
t2.shape

(3, 2, 4)

In [33]:
# 넘파이는 두 축을 바꾸는 swapaxes 함수를 제공
# t.transpose((1, 0 , 2))와 동일
t3 = t.swapaxes(0, 1)
t3

array([[[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]],

       [[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]]])

In [34]:
t3.shape

(2, 4, 3)