<a href="https://colab.research.google.com/github/JaeHeee/NumPy_Tutorial/blob/master/code/%EB%B0%B0%EC%97%B4_%ED%81%AC%EA%B8%B0_%EB%B3%80%EA%B2%BD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 배열 크기 변경

In [1]:
import numpy as np

### 자신을 변경

In [3]:
# ndarray의 shape 속성을 지정하면 간단히 크기를 바꿀 수 있다. 배열의 원소 개수는 동일하게 유지된다.
g = np.arange(24)
print(g)
print("랭크:", g.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
랭크: 1


In [4]:
g.shape = (6, 4)
print(g)
print("랭크:", g.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
랭크: 2


In [5]:
g.shape = (2, 3, 4)
print(g)
print("랭크:", g.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
랭크: 3


#### reshape

In [6]:
# reshape 함수는 동일한 데이터를 가리키는 새로운 ndarray 객체를 반환한다. 한 배열을 수정하면 다른 것도 함께 바뀐다.
g2 = g.reshape(4, 6)
print(g2)
print("랭크:", g2.ndim)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
랭크: 2


In [7]:
g2[1, 2] = 999
g2

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7, 999,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23]])

In [8]:
g

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [999,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])

#### ravel

In [9]:
# ravel 함수는 동일한 데이터를 가리키는 새로운 1차원 ndarray를 반환한다.
g.ravel()

array([  0,   1,   2,   3,   4,   5,   6,   7, 999,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])