<a href="https://colab.research.google.com/github/JaeHeee/NumPy_Tutorial/blob/master/code/%EB%B0%B0%EC%97%B4_%EC%9D%B8%EB%8D%B1%EC%8B%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 배열 인덱싱

In [3]:
import numpy as np

### 1차원 배열

In [4]:
# 1차원 넘파이 배열은 보통의 파이썬 배열과 비슷하게 사용 가능
a = np.array([1, 5, 3, 19, 13, 7, 3])
a[3]

19

In [5]:
a[2:5]

array([ 3, 19, 13])

In [6]:
a[2:-1]

array([ 3, 19, 13,  7])

In [7]:
a[:2]

array([1, 5])

In [8]:
a[::-1]

array([ 3,  7, 13, 19,  3,  5,  1])

In [10]:
a[3]=999
a

array([  1,   5,   3, 999,  13,   7,   3])

In [11]:
a[2:5] = [997, 998, 999]
a

array([  1,   5, 997, 998, 999,   7,   3])

### 보통의 파이썬 배열과 차이점

In [12]:
# 보통의 파이썬 배열과 대조적으로 ndarray 슬라이싱에 하나의 값을 할당하면 슬라이싱 전체에 복사된다.
a[2:5] = -1
a

array([ 1,  5, -1, -1, -1,  7,  3])

In [14]:
# ndarray 크기를 늘리거나 줄일 수 없다.
try:
    a[2:5] = [1, 2, 3, 4, 5, 6]
except ValueError as e:
    print(e)

cannot copy sequence with size 6 to array axis with dimension 3


In [15]:
# 원소를 삭제할 수도 없다.
try:
    del a[2:5]
except ValueError as e:
    print(e)

cannot delete array elements


In [16]:
# ndarray의 슬라이싱은 같은 데이터 버퍼를 바라보는 뷰(view)이다. 슬라이싱된 객체를 수정하면 실제 원본 ndarray가 수정된다.
a_slice = a[2:6]
a_slice[1] = 1000
a

array([   1,    5,   -1, 1000,   -1,    7,    3])

In [17]:
a[3] = 2000
a_slice

array([  -1, 2000,   -1,    7])

In [18]:
# 데이터를 복사하려면 copy 메서드를 사용해야 한다.
another_slice = a[2:6].copy()
another_slice[1] = 3000
a

array([   1,    5,   -1, 2000,   -1,    7,    3])

In [19]:
a[3] = 4000
another_slice

array([  -1, 3000,   -1,    7])

### 다차원 배열

In [20]:
# 다차원 배열은 비슷한 방식으로 각 축을 따라 인덱싱 또는 슬라이싱해서 사용. 콤마로 구분
b = np.arange(48).reshape(4, 12)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]])

In [21]:
b[1, 2]

14

In [23]:
b[:, 1]

array([ 1, 13, 25, 37])

In [24]:
# (12, ) 크기인 1D 배열로 행이 하나
b[1, :]

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [25]:
# (1, 12) 크기인 2D 배열로 같은 행을 반환
b[1:2, :]

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

### 팬시 인덱싱(Fancy indexing)

In [26]:
# 관심 대상의 인덱스 리스트를 지정할 수도 있다.
# 행 0, 2 열 2~4
b[(0,2), 2:5]

array([[ 2,  3,  4],
       [26, 27, 28]])

In [27]:
# 모든 행, 열 -1, 2, -1
b[:, (-1, 2, -1)]

array([[11,  2, 11],
       [23, 14, 23],
       [35, 26, 35],
       [47, 38, 47]])

In [28]:
# 여러 개의 인덱스 리스트를 지정하면 인덱스에 맞는 값이 포함된 1D ndarray를 반환
b[(-1, 2, -1, 2), (5, 9, 1, 9)]

array([41, 33, 37, 33])

### 고차원

In [29]:
# 고차원에서도 동일한 방식 적용
c = b.reshape(4,2,6)
c

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]],

       [[36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]]])

In [30]:
c[2, 1, 4]

34

In [31]:
c[2, :, 3]

array([27, 33])

In [32]:
c[2, 1]

array([30, 31, 32, 33, 34, 35])

### 생략 부호(...)

In [37]:
# 생략 부호를 쓰면 모든 지정하지 않은 축의 원소를 포함한다.
# c[2, :, :] 와 동일
c[2, ...]

array([[24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [39]:
# c[2, 1, :] 와 동일
c[2, 1, ...]

array([30, 31, 32, 33, 34, 35])

In [40]:
# c[2, :, 3] 와 동일
c[2, ..., 3]

array([27, 33])

In [41]:
# c[:, :, 3] 와 동일
c[..., 3]

array([[ 3,  9],
       [15, 21],
       [27, 33],
       [39, 45]])

### 불리언 인덱싱

In [42]:
# 불리언 값을 가진 ndarray를 사용해 축의 인덱스를 지정 가능
b = np.arange(48).reshape(4, 12)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]])

In [43]:
# b[(0, 2), :] 와 동일
rows_on = np.array([True, False, True, False])
b[rows_on, :]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [48]:
# 모든 행, 열 1, 4, 7, 10
cols_on = np.array([False, True, False]*4)
b[:, cols_on]

array([[ 1,  4,  7, 10],
       [13, 16, 19, 22],
       [25, 28, 31, 34],
       [37, 40, 43, 46]])

#### np.ix_

In [46]:
# 여러 축에 걸쳐서는 불리언 인덱싱을 사용할 수 없고, ix_ 함수를 사용한다.
b[np.ix_(rows_on, cols_on)]

array([[ 1,  4,  7, 10],
       [25, 28, 31, 34]])

In [47]:
np.ix_(rows_on, cols_on)

(array([[0],
        [2]]), array([[ 1,  4,  7, 10]]))

In [49]:
# ndarray와 같은 크기의 불리언 배열을 사용하면 해당 위치가 True인 모든 원소를 담은 1D 배열이 반환된다.
# 일반적으로 조건 연산자와 함께 사용
b[b % 3 == 1]

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46])