<a href="https://colab.research.google.com/github/JaeHeee/NumPy_Tutorial/blob/master/code/%EC%82%B0%EC%88%A0_%EC%97%B0%EC%82%B0%2C_%EB%B8%8C%EB%A1%9C%EB%93%9C%EC%BA%90%EC%8A%A4%ED%8C%85.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 산술 연산, 브로드캐스팅

In [1]:
import numpy as np

## 산술 연산

In [2]:
# 일반적인 산술 연산자(+, -, *, /, //, ** 등)는 모두 ndarray와 사용할 수 있다.
# 배열의 크기는 같아야 한다. 그렇지 않으면 넘파이가 브로드캐스팅 규칙을 적용한다.
a = np.array([14, 23, 32, 41])
b = np.array([5, 4, 3, 2])
print("a + b =", a + b)
print("a - b =", a - b)
print("a * b =", a * b)
print("a / b =", a / b)
print("a // b =", a // b)
print("a % b =", a % b)
print("a ** b =", a ** b)

a + b = [19 27 35 43]
a - b = [ 9 19 29 39]
a * b = [70 92 96 82]
a / b = [ 2.8         5.75       10.66666667 20.5       ]
a // b = [ 2  5 10 20]
a % b = [4 3 2 1]
a ** b = [537824 279841  32768   1681]


## 브로드캐스팅

일반적으로 넘파이는 동일한 크기의 배열을 기대한다. 그렇지 않은 상황에는 브로드캐스팅 규칙을 적용한다.

### 규칙 1

In [3]:
# 배열의 랭크가 동일하지 않으면 랭크가 맞을 때까지 랭크가 작은 배열 앞에 1을 추가한다.
h = np.arange(5).reshape(1, 1, 5)
h

array([[[0, 1, 2, 3, 4]]])

In [4]:
# 여기에 (1, 1, 5) 크기의 3D 배열에 (5, ) 크기의 1D 배열을 더하면 브로드캐스팅 규칙 1이 적용된다.
h + [10, 20, 30, 40, 50]

array([[[10, 21, 32, 43, 54]]])

### 규칙 2

In [5]:
# 특정 차원이 1인 배열은 그 차원에서 크기가 가장 큰 배열의 크기에 맞춰 동작한다. 배열의 원소가 차원을 따라 반복
k = np.arange(6).reshape(2, 3)
k

array([[0, 1, 2],
       [3, 4, 5]])

In [6]:
# (2, 3) 크기의 2D ndarray에 (2,1) 크기의 2D 배열을 더하면 넘파이는 브로드캐스팅 규칙 2를 적용한다.
# 다음과 같다: k +[[100, 100, 100], [200, 200, 200]]
k + [[100], [200]]

array([[100, 101, 102],
       [203, 204, 205]])

In [7]:
# 규칙 1과 규칙 2를 합치면 다음과 같이 동작한다.
# 규칙 1 적용 : [[100, 200, 300]]
# 규칙 2 적요 : [[100, 200, 300], [100 ,200, 300]]
k + [100, 200, 300]

array([[100, 201, 302],
       [103, 204, 305]])

In [8]:
# 다음과 같이도 가능
# k + [[1000, 1000, 1000], [1000, 1000, 1000]]
k + 1000

array([[1000, 1001, 1002],
       [1003, 1004, 1005]])

### 규칙 3

In [9]:
# 규칙 1과 2를 적용했을 때 모든 배열의 크기가 맞아야 한다.
try:
    k + [33, 44]
except ValueError as e:
    print(e)

operands could not be broadcast together with shapes (2,3) (2,) 


### 업캐스팅

In [11]:
# dtype이 다른 배열을 합칠 때 넘파이는 모든 값을 다룰 수 있는 타입으로 업캐스팅한다.
k1 = np.arange(0, 5, dtype=np.uint8)
print(k1.dtype, k1)

uint8 [0 1 2 3 4]


In [12]:
k2 = k1 + np.array([5, 6, 7, 8, 9], dtype=np.int8)
print(k2.dtype, k2)

int16 [ 5  7  9 11 13]


In [13]:
# 모든 int8과 uint8 값(-128에서 255까지)을 표현하기 위해 int16이 필요하다.
# 다음 코드에서는 uint8이면 충분하지만 업캐스팅되었다.
k3 = k1 + 1.5
print(k3.dtype, k3)

float64 [1.5 2.5 3.5 4.5 5.5]
