<a href="https://colab.research.google.com/github/JaeHeee/NumPy_Tutorial/blob/master/code/%EC%84%A0%ED%98%95_%EB%8C%80%EC%88%98%ED%95%99.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 선형 대수학

In [1]:
import numpy as np

넘파이 2D 배열을 사용하면 파이썬에서 행렬을 효율적으로 표현할 수 있다.

### 행렬 전치

In [2]:
# T 속성은 랭크가 2보다 크거나 같을 때 transpose()를 호출하는 것과 같다.
m1 = np.arange(10).reshape(2, 5)
m1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [3]:
m1.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [4]:
# T 속성은 랭크가 0이거나 1인 배열에는 아무런 영향을 미치지 않는다.
m2 = np.arange(5)
m2

array([0, 1, 2, 3, 4])

In [5]:
m2.T

array([0, 1, 2, 3, 4])

In [6]:
# 먼저 1D 배열을 하나의 행이 있는 행렬(2D)로 바꾼다음 전치를 수행할 수 있다.
m2r = m2.reshape(1, 5)
m2r

array([[0, 1, 2, 3, 4]])

In [7]:
m2r.T

array([[0],
       [1],
       [2],
       [3],
       [4]])

### 행렬 점곱

In [8]:
# 두 개의 행렬을 만들어 dot 메서드로 행렬 점곱을 실행
n1 = np.arange(10).reshape(2, 5)
n1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
n2 = np.arange(15).reshape(5, 3)
n2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [10]:
n1.dot(n2)

array([[ 90, 100, 110],
       [240, 275, 310]])

n1*n2는 점곱이 아니라 원소별 곱셈

### 역행렬과 유사 역행렬

In [12]:
# numpy.linalg 모듈 안에 많은 선형 대수 함수들이 있다. 특히 inv 함수는 정방 행렬의 역행렬을 계산
import numpy.linalg as linalg

m3 = np.array([[1,2,3],[5,7,11],[21,29,31]])
m3

array([[ 1,  2,  3],
       [ 5,  7, 11],
       [21, 29, 31]])

In [13]:
linalg.inv(m3)

array([[-2.31818182,  0.56818182,  0.02272727],
       [ 1.72727273, -0.72727273,  0.09090909],
       [-0.04545455,  0.29545455, -0.06818182]])

In [14]:
# pinv 함수를 사용하여 유사 역행렬을 계산할 수 있다.
linalg.pinv(m3)

array([[-2.31818182,  0.56818182,  0.02272727],
       [ 1.72727273, -0.72727273,  0.09090909],
       [-0.04545455,  0.29545455, -0.06818182]])

### 단위 행렬

In [15]:
# 행렬과 그 행렬의 역행렬을 곱하면 단위 행렬이 된다.
m3.dot(linalg.inv(m3))

array([[ 1.00000000e+00, -1.66533454e-16,  0.00000000e+00],
       [ 6.31439345e-16,  1.00000000e+00, -1.38777878e-16],
       [ 5.21110932e-15, -2.38697950e-15,  1.00000000e+00]])

In [16]:
# eye 함수는 NxN 크기의 단위 행렬을 생성
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### QR 분해

In [17]:
# qr 함수는 행렬을 QR 분해한다.
q, r = linalg.qr(m3)
q

array([[-0.04627448,  0.98786672,  0.14824986],
       [-0.23137241,  0.13377362, -0.96362411],
       [-0.97176411, -0.07889213,  0.22237479]])

In [18]:
r

array([[-21.61018278, -29.89331494, -32.80860727],
       [  0.        ,   0.62427688,   1.9894538 ],
       [  0.        ,   0.        ,  -3.26149699]])

In [19]:
# q.dot(r)는 m3와 같다.
q.dot(r)

array([[ 1.,  2.,  3.],
       [ 5.,  7., 11.],
       [21., 29., 31.]])

### 행렬식

In [20]:
# det 함수는 행렬식을 계산
linalg.det(m3)

43.99999999999997

### 고유값과 고유벡터

In [21]:
# eig 함수는 정방 행렬의 고유값과 고유벡터를 계산
eigenvalues, eigenvectors = linalg.eig(m3)
eigenvalues

array([42.26600592, -0.35798416, -2.90802176])

In [22]:
eigenvectors

array([[-0.08381182, -0.76283526, -0.18913107],
       [-0.3075286 ,  0.64133975, -0.6853186 ],
       [-0.94784057, -0.08225377,  0.70325518]])

In [23]:
# m3.v - λ*v = 0
m3.dot(eigenvectors) - eigenvalues * eigenvectors

array([[ 6.66133815e-15,  1.66533454e-15, -3.10862447e-15],
       [ 7.10542736e-15,  5.16253706e-15, -5.32907052e-15],
       [ 3.55271368e-14,  4.94743135e-15, -9.76996262e-15]])

### 특이값 분해


In [25]:
# svd 함수는 행렬을 입력으로 받아 그 행렬의 특이값 분해를 반환
m4 = np.array([[1,0,0,0,2], [0,0,3,0,0], [0,0,0,0,0], [0,2,0,0,0]])
m4

array([[1, 0, 0, 0, 2],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0]])

In [26]:
U, S_diag, V = linalg.svd(m4)

In [27]:
U

array([[ 0.,  1.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -1.],
       [ 0.,  0.,  1.,  0.]])

In [28]:
S_diag

array([3.        , 2.23606798, 2.        , 0.        ])

In [29]:
# svd 함수는 Σ의 대각 원소 값만 반환. 전체 Σ 행렬은 다음과 같이 생성
S = np.zeros((4, 5))
S[np.diag_indices(4)] = S_diag
S

array([[3.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 2.23606798, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 2.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

In [30]:
V

array([[-0.        ,  0.        ,  1.        , -0.        ,  0.        ],
       [ 0.4472136 ,  0.        ,  0.        ,  0.        ,  0.89442719],
       [-0.        ,  1.        ,  0.        , -0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ,  0.        ],
       [-0.89442719,  0.        ,  0.        ,  0.        ,  0.4472136 ]])

In [31]:
# U.Σ.V == m4
U.dot(S).dot(V)

array([[1., 0., 0., 0., 2.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.]])

### 대각원소와 대각합

In [32]:
# m3의 대각 원소
np.diag(m3)

array([ 1,  7, 31])

In [33]:
# np.diag(m3).sum()
np.trace(m3)

39

### 선형 방정식 풀기

In [35]:
# solve 함수는 다음과 같은 선형 방정식을 푼다.
# 2x + 6y = 6
# 5x + 3y = -9
coeffs = np.array([[2, 6], [5, 3]])
depvars = np.array([6, -9])
solution = linalg.solve(coeffs, depvars)
solution

array([-3.,  2.])

In [36]:
coeffs.dot(solution), depvars

(array([ 6., -9.]), array([ 6, -9]))

In [37]:
np.allclose(coeffs.dot(solution), depvars)

True